-- Structured provenance for split items plus the initial Blaze Black early-game catalogue.
BEGIN;
SELECT pg_advisory_xact_lock(hashtext('lockley:blazeblack_split_item_sources_v1'));
CREATE TABLE IF NOT EXISTS schema_migrations (
    migration_name text PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT current_timestamp
);
CREATE TABLE IF NOT EXISTS curated_split_item_sources (
    item_source_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_record_id bigint NOT NULL REFERENCES curated_split_items(item_record_id) ON DELETE CASCADE,
    source_key text NOT NULL CHECK (length(source_key) BETWEEN 1 AND 160),
    method_kind text NOT NULL CHECK (method_kind IN ('thief', 'dust_cloud', 'conditional', 'manual')),
    source_species_id integer,
    chance_percent numeric(5,2) CHECK (chance_percent IS NULL OR chance_percent BETWEEN 0 AND 100),
    source_detail text,
    source_url text,
    sort_order integer NOT NULL DEFAULT 0,
    UNIQUE (item_record_id, source_key)
);
CREATE INDEX IF NOT EXISTS curated_split_item_sources_item_idx
    ON curated_split_item_sources(item_record_id, sort_order);
ALTER TABLE curated_split_item_sources ENABLE ROW LEVEL SECURITY;

-- Preserve items entered through the original split/item/method editor.
INSERT INTO curated_split_item_sources(item_record_id, source_key, method_kind, source_detail)
SELECT item_record_id, 'manual:legacy', 'manual', method
FROM curated_split_items item
WHERE NOT EXISTS (
    SELECT 1 FROM curated_split_item_sources src WHERE src.item_record_id = item.item_record_id
)
AND NOT EXISTS (
    SELECT 1 FROM schema_migrations WHERE migration_name = 'blazeblack_split_item_sources_v1'
);

CREATE TEMP TABLE _bb_split_sources (
    split_key text, item_name text, source_key text, method_kind text,
    species_id integer, chance numeric(5,2), detail text, source_url text, sort_order integer
) ON COMMIT DROP;

INSERT INTO _bb_split_sources VALUES
-- Lenora: held items available through Thief before the second badge.
('badge:34','Big Pearl','thief:90','thief',90,5,'Shellder','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Black Belt','thief:538','thief',538,5,'Throh · Pinwheel Forest Outside','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Black Belt','thief:539','thief',539,5,'Sawk · Pinwheel Forest Outside','https://www.serebii.net/blackwhite/holditems.shtml',101),
('badge:34','Black Sludge','thief:453','thief',453,5,'Croagunk · Pinwheel Forest Outside','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Charti Berry','thief:276','thief',276,5,'Taillow','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Cheri Berry','thief:522','thief',522,50,'Blitzle','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Chesto Berry','thief:327','thief',327,5,'Spinda','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Chesto Berry','thief:293','thief',293,5,'Whismur','https://www.serebii.net/blackwhite/holditems.shtml',101),
('badge:34','Chilan Berry','thief:19','thief',19,5,'Rattata','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Coba Berry','thief:191','thief',191,5,'Sunkern','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Colbur Berry','conditional:433','conditional',433,5,'Pickup or Covet · Thief’s Dark hit consumes the berry','https://www.serebii.net/blackwhite/holditems.shtml',300),
('badge:34','Comet Shard','thief:35','thief',35,1,'Clefairy','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Comet Shard','thief:173','thief',173,1,'Cleffa','https://www.serebii.net/blackwhite/holditems.shtml',101),
('badge:34','Comet Shard','thief:337','thief',337,1,'Lunatone','https://www.serebii.net/blackwhite/holditems.shtml',102),
('badge:34','Comet Shard','thief:338','thief',338,1,'Solrock','https://www.serebii.net/blackwhite/holditems.shtml',103),
('badge:34','Deep Sea Scale','thief:170','thief',170,5,'Chinchou','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Deep Sea Tooth','thief:550','thief',550,5,'Basculin','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Dragon Scale','thief:147','thief',147,5,'Dratini','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Everstone','thief:74','thief',74,5,'Geodude · Wellspring Cave 1F','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Everstone','thief:524','thief',524,50,'Roggenrola · Wellspring Cave 1F','https://www.serebii.net/blackwhite/holditems.shtml',101),
('badge:34','Expert Belt','thief:538','thief',538,1,'Throh · Pinwheel Forest Outside','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Expert Belt','thief:539','thief',539,1,'Sawk · Pinwheel Forest Outside','https://www.serebii.net/blackwhite/holditems.shtml',101),
('badge:34','Haban Berry','thief:443','thief',443,5,'Gible · Wellspring Cave 1F','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Hard Stone','thief:524','thief',524,5,'Roggenrola · Wellspring Cave 1F','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Hard Stone','thief:304','thief',304,5,'Aron · Wellspring Cave 1F','https://www.serebii.net/blackwhite/holditems.shtml',101),
('badge:34','Lagging Tail','thief:79','thief',79,5,'Slowpoke','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Leppa Berry','thief:300','thief',300,5,'Skitty','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Leppa Berry','thief:35','thief',35,50,'Clefairy','https://www.serebii.net/blackwhite/holditems.shtml',101),
('badge:34','Leppa Berry','thief:173','thief',173,50,'Cleffa','https://www.serebii.net/blackwhite/holditems.shtml',102),
('badge:34','Lucky Egg','thief:440','thief',440,5,'Happiny','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Metal Coat','thief:436','thief',436,5,'Bronzor · Wellspring Cave 1F','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Metronome','thief:401','thief',401,5,'Kricketot','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Moon Stone','thief:35','thief',35,5,'Clefairy','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Moon Stone','thief:173','thief',173,5,'Cleffa','https://www.serebii.net/blackwhite/holditems.shtml',101),
('badge:34','Moon Stone','thief:337','thief',337,5,'Lunatone','https://www.serebii.net/blackwhite/holditems.shtml',102),
('badge:34','Oran Berry','thief:161','thief',161,5,'Sentret','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Oran Berry','thief:263','thief',263,5,'Zigzagoon','https://www.serebii.net/blackwhite/holditems.shtml',101),
('badge:34','Oran Berry','thief:531','thief',531,50,'Audino','https://www.serebii.net/blackwhite/holditems.shtml',102),
('badge:34','Oval Stone','thief:440','thief',440,50,'Happiny','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Passho Berry','thief:231','thief',231,5,'Phanpy','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Payapa Berry','thief:56','thief',56,5,'Mankey','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Pearl','thief:90','thief',90,50,'Shellder','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Pecha Berry','thief:261','thief',261,5,'Poochyena','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Persim Berry','thief:535','thief',535,50,'Tympole · Pinwheel Forest Outside','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Poison Barb','thief:15','thief',15,5,'Beedrill','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Poison Barb','thief:406','thief',406,5,'Budew','https://www.serebii.net/blackwhite/holditems.shtml',101),
('badge:34','Poison Barb','thief:211','thief',211,5,'Qwilfish','https://www.serebii.net/blackwhite/holditems.shtml',102),
('badge:34','Poison Barb','thief:72','thief',72,5,'Tentacool','https://www.serebii.net/blackwhite/holditems.shtml',103),
('badge:34','Quick Claw','thief:52','thief',52,5,'Meowth','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Rawst Berry','thief:58','thief',58,100,'Growlithe','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Rawst Berry','thief:37','thief',37,100,'Vulpix','https://www.serebii.net/blackwhite/holditems.shtml',101),
('badge:34','Sharp Beak','thief:84','thief',84,5,'Doduo · Pinwheel Forest Outside','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Shed Shell','thief:267','thief',267,5,'Beautifly','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Shed Shell','thief:269','thief',269,5,'Dustox','https://www.serebii.net/blackwhite/holditems.shtml',101),
('badge:34','Shed Shell','thief:49','thief',49,5,'Venomoth','https://www.serebii.net/blackwhite/holditems.shtml',102),
('badge:34','Silver Powder','thief:12','thief',12,5,'Butterfree','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Sitrus Berry','thief:531','thief',531,5,'Audino','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Soft Sand','thief:50','thief',50,5,'Diglett · Wellspring Cave 1F','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Star Piece','thief:120','thief',120,5,'Staryu','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Star Piece','thief:385','thief',385,100,'Jirachi','https://www.serebii.net/blackwhite/holditems.shtml',101),
('badge:34','Stardust','thief:120','thief',120,50,'Staryu','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Sun Stone','thief:338','thief',338,5,'Solrock','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Thick Club','thief:104','thief',104,5,'Cubone · Pinwheel Forest Outside','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Twisted Spoon','thief:63','thief',63,5,'Abra','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:34','Yache Berry','thief:396','thief',396,5,'Starly','https://www.serebii.net/blackwhite/holditems.shtml',100),
-- Lenora: Wellspring Cave 1F dust-cloud items. Chance is per dust cloud.
('badge:34','Fire Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Water Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Electric Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Grass Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Ice Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Fighting Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Poison Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Ground Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Flying Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Psychic Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Bug Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Rock Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Ghost Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Dragon Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Dark Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Steel Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Normal Gem','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F · Gem','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Sun Stone','dust:wellspring-1f','dust_cloud',NULL,0.6,'Wellspring Cave 1F · Stone','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Moon Stone','dust:wellspring-1f','dust_cloud',NULL,0.6,'Wellspring Cave 1F · Stone','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Fire Stone','dust:wellspring-1f','dust_cloud',NULL,0.6,'Wellspring Cave 1F · Stone','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Water Stone','dust:wellspring-1f','dust_cloud',NULL,0.6,'Wellspring Cave 1F · Stone','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Thunder Stone','dust:wellspring-1f','dust_cloud',NULL,0.6,'Wellspring Cave 1F · Stone','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Leaf Stone','dust:wellspring-1f','dust_cloud',NULL,0.6,'Wellspring Cave 1F · Stone','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Shiny Stone','dust:wellspring-1f','dust_cloud',NULL,0.6,'Wellspring Cave 1F · Stone','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Dusk Stone','dust:wellspring-1f','dust_cloud',NULL,0.6,'Wellspring Cave 1F · Stone','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Dawn Stone','dust:wellspring-1f','dust_cloud',NULL,0.6,'Wellspring Cave 1F · Stone','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Oval Stone','dust:wellspring-1f','dust_cloud',NULL,0.6,'Wellspring Cave 1F · Stone','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
('badge:34','Everstone','dust:wellspring-1f','dust_cloud',NULL,3,'Wellspring Cave 1F','https://bulbapedia.bulbagarden.net/wiki/Phenomenon',200),
-- Burgh: only newly available held items from Pinwheel Forest Inside.
('badge:35','Kebia Berry','thief:285','thief',285,5,'Shroomish · Pinwheel Forest Inside','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:35','King''s Rock','thief:61','thief',61,5,'Poliwhirl · Pinwheel Forest Inside','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:35','King''s Rock','thief:186','thief',186,5,'Politoed · Pinwheel Forest Inside','https://www.serebii.net/blackwhite/holditems.shtml',101),
('badge:35','Mental Herb','thief:540','thief',540,5,'Sewaddle · Pinwheel Forest Inside','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:35','Mental Herb','thief:541','thief',541,5,'Swadloon · Pinwheel Forest Inside','https://www.serebii.net/blackwhite/holditems.shtml',101),
('badge:35','Occa Berry','thief:511','thief',511,5,'Pansage · Pinwheel Forest Inside','https://www.serebii.net/blackwhite/holditems.shtml',100),
('badge:35','Rindo Berry','thief:515','thief',515,5,'Panpour · Pinwheel Forest Inside','https://www.serebii.net/blackwhite/holditems.shtml',100);

WITH modes AS (
    SELECT split_key, item_name,
        CASE
            WHEN bool_or(method_kind = 'conditional') THEN 'Conditional'
            WHEN bool_or(method_kind = 'thief') AND bool_or(method_kind = 'dust_cloud') THEN 'Multiple sources'
            WHEN bool_or(method_kind = 'dust_cloud') THEN 'Dust cloud'
            ELSE 'Thief'
        END AS method
    FROM _bb_split_sources GROUP BY split_key, item_name
)
INSERT INTO curated_split_items(game_id, split_key, item_name, method)
SELECT 1001, modes.split_key, modes.item_name, modes.method FROM modes
WHERE EXISTS (SELECT 1 FROM games WHERE game_id = 1001)
AND NOT EXISTS (
    SELECT 1 FROM curated_split_items item
    WHERE item.game_id = 1001 AND item.split_key = modes.split_key AND item.item_name = modes.item_name
);

INSERT INTO curated_split_item_sources(
    item_record_id, source_key, method_kind, source_species_id,
    chance_percent, source_detail, source_url, sort_order
)
SELECT item.item_record_id, src.source_key, src.method_kind, src.species_id,
       src.chance, src.detail, src.source_url, src.sort_order
FROM _bb_split_sources src
JOIN LATERAL (
    SELECT item_record_id FROM curated_split_items
    WHERE game_id = 1001 AND split_key = src.split_key AND item_name = src.item_name
    ORDER BY item_record_id LIMIT 1
) item ON true
ON CONFLICT (item_record_id, source_key) DO UPDATE SET
    method_kind = excluded.method_kind,
    source_species_id = excluded.source_species_id,
    chance_percent = excluded.chance_percent,
    source_detail = excluded.source_detail,
    source_url = excluded.source_url,
    sort_order = excluded.sort_order;

INSERT INTO schema_migrations(migration_name) VALUES ('blazeblack_split_item_sources_v1')
ON CONFLICT DO NOTHING;
COMMIT;
