-- Shared, game-scoped item curation and immutable attempt battle snapshots.
-- No sample items or reconstructed historical parties are seeded.
BEGIN;
SELECT pg_advisory_xact_lock(hashtext('lockley:split_timeline_v1'));
CREATE TABLE IF NOT EXISTS schema_migrations (
    migration_name text PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT current_timestamp
);
CREATE TABLE IF NOT EXISTS curated_split_items (
    item_record_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id integer NOT NULL REFERENCES games(game_id),
    split_key text NOT NULL CHECK (length(split_key) BETWEEN 1 AND 240),
    item_name text NOT NULL CHECK (length(trim(item_name)) BETWEEN 1 AND 100),
    method text NOT NULL CHECK (length(trim(method)) BETWEEN 1 AND 500),
    created_at timestamptz NOT NULL DEFAULT current_timestamp,
    updated_at timestamptz NOT NULL DEFAULT current_timestamp,
    UNIQUE (game_id, split_key, item_name, method)
);
CREATE TABLE IF NOT EXISTS attempt_battle_records (
    battle_record_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id integer NOT NULL REFERENCES attempts(attempt_id) ON DELETE CASCADE,
    trainer_id integer NOT NULL,
    boss_event_id integer,
    split_key text,
    party jsonb NOT NULL CHECK (jsonb_typeof(party) = 'array'),
    recorded_at timestamptz NOT NULL DEFAULT current_timestamp,
    UNIQUE (attempt_id, trainer_id)
);
CREATE INDEX IF NOT EXISTS attempt_battle_records_split_idx
    ON attempt_battle_records(attempt_id, split_key);
-- The Flask API owns access checks; do not expose either table through
-- Supabase's direct anonymous/authenticated PostgREST roles.
ALTER TABLE curated_split_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE attempt_battle_records ENABLE ROW LEVEL SECURITY;
-- Encounter keys remain stable across content reloads; event/trainer ids
-- are recorded for provenance but deliberately have no content-table FK.
-- Repair the known typo. Missing focus values remain unset, never guessed.
UPDATE event_bosses SET type_focus = 'Ice'
WHERE lower(trim(type_focus)) = 'iice';
INSERT INTO schema_migrations(migration_name) VALUES ('split_timeline_v1')
ON CONFLICT DO NOTHING;
COMMIT;
